image: node:22

stages:
  - deploy

.setup: &setup
  before_script:
    - npm install -g pnpm vercel
    - pnpm install

deploy_web_prod:
  <<: *setup
  stage: deploy
  script:
    - TOKEN="$VERCEL_TOKEN"
    - pnpm turbo run build --filter=@dep-incubation-dashboard/web --force
    - cd apps/web
    - VERCEL_ORG_ID="team_jWzoJccjWNuoTy4WE8Cgzslb" VERCEL_PROJECT_ID="prj_59InRSACCzLHSfXxIGezfKpadHSd" vercel build --prod --token=$TOKEN
    - VERCEL_ORG_ID="team_jWzoJccjWNuoTy4WE8Cgzslb" VERCEL_PROJECT_ID="prj_59InRSACCzLHSfXxIGezfKpadHSd" vercel deploy --prebuilt --prod --token=$TOKEN
  only:
    - dev

deploy_api_prod:
  <<: *setup
  stage: deploy
  script:
    - TOKEN="$VERCEL_TOKEN"
    - pnpm turbo run build --filter=@dep-incubation-dashboard/api --force
    - cd apps/api
    - VERCEL_ORG_ID="team_jWzoJccjWNuoTy4WE8Cgzslb" VERCEL_PROJECT_ID="prj_N8kBoeHuskRrA8Jeo4mTguED5jWS" vercel build --prod --token=$TOKEN
    - VERCEL_ORG_ID="team_jWzoJccjWNuoTy4WE8Cgzslb" VERCEL_PROJECT_ID="prj_N8kBoeHuskRrA8Jeo4mTguED5jWS" vercel deploy --prebuilt --prod --token=$TOKEN
  only:
    - dev

deploy_web_uat:
  <<: *setup
  stage: deploy
  script:
    - TOKEN="$VERCEL_TOKEN"
    - pnpm turbo run build --filter=@dep-incubation-dashboard/web --force
    - cd apps/web
    - VERCEL_ORG_ID="team_jWzoJccjWNuoTy4WE8Cgzslb" VERCEL_PROJECT_ID="prj_5Kt3holOWeGDesen12S4pGrsvMiF" vercel build --prod --token=$TOKEN
    - VERCEL_ORG_ID="team_jWzoJccjWNuoTy4WE8Cgzslb" VERCEL_PROJECT_ID="prj_5Kt3holOWeGDesen12S4pGrsvMiF" vercel deploy --prebuilt --prod --token=$TOKEN
  only:
    - UAT

deploy_api_uat:
  <<: *setup
  stage: deploy
  script:
    - TOKEN="$VERCEL_TOKEN"
    - pnpm turbo run build --filter=@dep-incubation-dashboard/api --force
    - cd apps/api
    - VERCEL_ORG_ID="team_jWzoJccjWNuoTy4WE8Cgzslb" VERCEL_PROJECT_ID="prj_cBoYxIR1ho95p9OmJLAcEGca6tpc" vercel build --prod --token=$TOKEN
    - VERCEL_ORG_ID="team_jWzoJccjWNuoTy4WE8Cgzslb" VERCEL_PROJECT_ID="prj_cBoYxIR1ho95p9OmJLAcEGca6tpc" vercel deploy --prebuilt --prod --token=$TOKEN
  only:
    - UAT
