image: node:22

stages:
  - deploy

.setup: &setup
  before_script:
    - npm install -g pnpm vercel
    - pnpm install

deploy_web_prod:
  <<: *setup
  stage: deploy
  script:
    - TOKEN="$VERCEL_TOKEN"
    - pnpm turbo run build --filter=@dep-incubation-dashboard/web --force
    - cd apps/web
    - mkdir -p .vercel
    - echo '{"projectId":"prj_59InRSACCzLHSfXxIGezfKpadHSd","orgId":"team_jWzoJccjWNuoTy4WE8Cgzslb"}' > .vercel/project.json
    - vercel pull --yes --environment=production --token=$TOKEN
    - echo '{"projectId":"prj_59InRSACCzLHSfXxIGezfKpadHSd","orgId":"team_jWzoJccjWNuoTy4WE8Cgzslb"}' > .vercel/project.json
    - vercel build --prod --token=$TOKEN
    - vercel deploy --prebuilt --prod --token=$TOKEN
  only:
    - dev

deploy_api_prod:
  <<: *setup
  stage: deploy
  script:
    - TOKEN="$VERCEL_TOKEN"
    - pnpm turbo run build --filter=@dep-incubation-dashboard/api --force
    - cd apps/api
    - mkdir -p .vercel
    - echo '{"projectId":"prj_N8kBoeHuskRrA8Jeo4mTguED5jWS","orgId":"team_jWzoJccjWNuoTy4WE8Cgzslb"}' > .vercel/project.json
    - vercel pull --yes --environment=production --token=$TOKEN
    - echo '{"projectId":"prj_N8kBoeHuskRrA8Jeo4mTguED5jWS","orgId":"team_jWzoJccjWNuoTy4WE8Cgzslb"}' > .vercel/project.json
    - vercel build --prod --token=$TOKEN
    - vercel deploy --prebuilt --prod --token=$TOKEN
  only:
    - dev

deploy_web_uat:
  <<: *setup
  stage: deploy
  script:
    - TOKEN="$VERCEL_TOKEN"
    - pnpm turbo run build --filter=@dep-incubation-dashboard/web --force
    - cd apps/web
    - mkdir -p .vercel
    - echo '{"projectId":"prj_5Kt3holOWeGDesen12S4pGrsvMiF","orgId":"team_jWzoJccjWNuoTy4WE8Cgzslb"}' > .vercel/project.json
    - vercel pull --yes --environment=production --token=$TOKEN
    - echo '{"projectId":"prj_5Kt3holOWeGDesen12S4pGrsvMiF","orgId":"team_jWzoJccjWNuoTy4WE8Cgzslb"}' > .vercel/project.json
    - vercel build --prod --token=$TOKEN
    - vercel deploy --prebuilt --prod --token=$TOKEN
  only:
    - UAT

deploy_api_uat:
  <<: *setup
  stage: deploy
  script:
    - TOKEN="$VERCEL_TOKEN"
    - pnpm turbo run build --filter=@dep-incubation-dashboard/api --force
    - cd apps/api
    - mkdir -p .vercel
    - echo '{"projectId":"prj_cBoYxIR1ho95p9OmJLAcEGca6tpc","orgId":"team_jWzoJccjWNuoTy4WE8Cgzslb"}' > .vercel/project.json
    - vercel pull --yes --environment=production --token=$TOKEN
    - echo '{"projectId":"prj_cBoYxIR1ho95p9OmJLAcEGca6tpc","orgId":"team_jWzoJccjWNuoTy4WE8Cgzslb"}' > .vercel/project.json
    - vercel build --prod --token=$TOKEN
    - vercel deploy --prebuilt --prod --token=$TOKEN
  only:
    - UAT
