import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.stories.{js,ts,jsx,tsx}", // include Storybook stories
  ],
  theme: {
    extend: {
      borderRadius: {
        sm: "calc(var(--radius) - 4px)",
        md: "calc(var(--radius) - 2px)",
        lg: "var(--radius)",
        xl: "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
        "3xl": "calc(var(--radius) + 12px)",
        "4xl": "calc(var(--radius) + 16px)",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        "chart-1": "var(--chart-1)",
        "chart-2": "var(--chart-2)",
        "chart-3": "var(--chart-3)",
        "chart-4": "var(--chart-4)",
        "chart-5": "var(--chart-5)",
        sidebar: "var(--sidebar)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        "sidebar-primary": "var(--sidebar-primary)",
        "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
        "sidebar-accent": "var(--sidebar-accent)",
        "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "sidebar-border": "var(--sidebar-border)",
        "sidebar-ring": "var(--sidebar-ring)",
        // Project palette
        "neutral-50": "#fafafc",
        "neutral-200": "#ebedf5",
        "neutral-400": "#ced0db",
        "neutral-500": "#acafbf",
        "neutral-700": "#474a59",
        "neutral-900": "#1d1e26",
        "success-50": "#fcfff5",
        "success-200": "#ebf3d8",
        "success-400": "#c1e288",
        "success-500": "#67a300",
        "success-700": "#528500",
        "success-900": "#396f1f",
        "warning-50": "#fffcf5",
        "warning-200": "#ffedc9",
        "warning-400": "#ffd785",
        "warning-500": "#fcaa00",
        "warning-700": "#ff9000",
        "warning-900": "#bd5800",
        "danger-50": "#fef6f6",
        "danger-200": "#fde1e1",
        "danger-400": "#fbb6b6",
        "danger-500": "#ff4242",
        "danger-700": "#e22a2a",
        "danger-900": "#ad0000",
        "primary-50": "#f5fdff",
        "primary-200": "#e1f4fa",
        "primary-400": "#a0ddee",
        "primary-500": "#009ecc",
        "primary-700": "#0086ad",
        "primary-900": "#006b8a",
      },
    },
  },
  plugins: [],
};

export default config;